### ISSUE TITLE
Kanban project

### ISSUE THREAD

**Issue by Amrhub** [RafaelEchart/RestaurantMenu_Capstone#21]
[Kanban Project](https://github.com/RafaelEchart/RestaurantMenu_Capstone/projects/1)

We are group of two people :)

**Comment by Amrhub** [comment]
I noticed that it links properly, but perhaps you would need to refresh it

**Comment by omar-labana** [comment]
Hi @Amrhub, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
